export interface ICreation {
  id: string
  slug: string
  title: string
  description: string
  icon: string
  image: string
  content: string
  podcast: any
  i18n: any
  props: any
  cid: string
  type: string
  gateType: string
  status: string
  commentStatus: string
  commentCount: number
  featured: boolean
  collectible: boolean
  delivered: boolean
  checked: boolean
  isPopular: boolean
  isJournal: boolean
  date?: string
  publishedAt?: Date
  archivedAt?: Date
  openedAt: Date
  createdAt: Date
  updatedAt: Date
  userId: string
  siteId: string
  areaId: string
  moldId: string
}
