const listCode = `
"use strict";(()=>{var o;(function(t){t.Render="Render",t.InitOnFilterChange="InitOnFilterChange",t.OnFilterChange="OnFilterChange",t.InitOnSearchChange="InitOnSearchChange",t.OnSearchChange="OnSearchChange"})(o||(o={}));function r(t){return t.type==="CustomAction"}function u(t){return t?.type==="action--custom-action"&&Reflect.has(t,"itemIndex")}function l(t){return t?.type==="onItemSelect"}var i=class{constructor(a){this.setState=s=>{let e=s?.items?.length?!1:this.state.isLoading;this.state={...this.state,isLoading:e,...s},this.render()},this.onSelectItem=s=>(this.onItemSelectCallback=s,this),this.run=()=>(this.render(),self.addEventListener("message",async s=>{if(u(s.data)){let n=this.state.items[s.data.itemIndex].actions[s.data.actionIndex];r(n)&&n.onClick?.()}if(l(s.data)){let e=this.state.items[s.data.itemIndex];if(typeof e.detail=="function"){postMessage({type:"detail",isLoading:!0,data:[]});let n=await e.detail();postMessage({type:"detail",isLoading:!1,data:n})}}}),this),this.render=()=>{postMessage({type:o.Render,payload:{type:"list",...this.formatState(this.state)}})},this.state={items:[],isLoading:!1,filtering:!0,titleLayout:"row",isShowingDetail:!1,...a}}formatState(a){let s=a.items.map(e=>({...e,detail:typeof e.detail=="function"?"functionDetail":e.detail,actions:e.actions?.map(n=>{if(!r(n))return n;let{onClick:h,...c}=n;return c})}));return{...this.state,items:s}}};async function d(){let t=new i({items:[]}).run(),a=Array(10).fill("").map((s,e)=>({icon:e+1,title:100+e.toString(),actions:[{type:"CopyToClipboard",content:e.toString()}]}));setTimeout(()=>{t.setState({items:a})},1)}d();})();
`

const formCode = `
"use strict";(()=>{var o;(function(t){t.Render="Render",t.InitOnFilterChange="InitOnFilterChange",t.OnFilterChange="OnFilterChange",t.InitOnSearchChange="InitOnSearchChange",t.OnSearchChange="OnSearchChange"})(o||(o={}));function r(t){return t.type==="SubmitForm"}function l(t){return t.type==="CustomAction"}function u(t){return t?.type==="action--on-submit"&&Reflect.has(t,"values")}var a=class{constructor(s){this.setState=n=>{this.state={...this.state,...n},this.render()},this.run=()=>(this.render(),self.addEventListener("message",async n=>{if(u(n.data)){let e=this.state.actions[n.data.actionIndex];r(e)&&e.onSubmit(n.data.values)}}),this),this.render=()=>{postMessage({type:o.Render,payload:{type:"form",...this.state,...this.formatState(this.state)}})},this.state={fields:[],isLoading:!1,...s}}formatState(s){let n=s.actions?.map(e=>{if(r(e)){let{onSubmit:c,...i}=e;return i}if(l(e)){let{onClick:c,...i}=e;return i}return e});return{...this.state,actions:n}}};function d(){let t=new a({fields:[{label:"First Name",name:"firstName",component:"Input"},{label:"Description",name:"description",component:"Textarea"},{label:"Open",name:"isOpen",component:"Switch",value:!0},{label:"Color",name:"color",component:"Select",options:[{label:"Red",value:"red"},{label:"Green",value:"green"},{label:"Blue",value:"blur"}],value:"red"}],actions:[{type:"SubmitForm",onSubmit:async s=>{console.log("======values:",s)}}]}).run()}d();})();
`

const markdownCode = `
"use strict";(()=>{var s;(function(t){t.Render="Render",t.InitOnFilterChange="InitOnFilterChange",t.OnFilterChange="OnFilterChange",t.InitOnSearchChange="InitOnSearchChange",t.OnSearchChange="OnSearchChange"})(s||(s={}));var e=class{constructor(a){this.setState=n=>{let i=n?.content?!1:this.state.isLoading;this.state={...this.state,isLoading:i,...n},this.render()},this.run=()=>(this.render(),this),this.render=()=>{postMessage({type:s.Render,payload:{type:"markdown",...this.state}})},this.state={isLoading:!1,...a}}};async function o(){new e({content:"# Hello world"}).run()}o();})();
`

export const builtCodeMap: Record<string, string> = {
  markdown: markdownCode,
  list: listCode,
  form: formCode,
}
