export enum EventType {
  Render = 'Render',

  RenderList = 'RenderList',
  RenderMarkdown = 'RenderMarkdown',
  Loading = 'Loading.',

  RunAppleScript = 'RunAppleScript',
  RunAppleScriptResult = 'RunAppleScriptResult',

  InitOnSearchChange = 'InitOnSearchChange',
  OnSearchChange = 'OnSearchChange',

  InitOnFilterChange = 'InitOnFilterChange',
  OnFilterChange = 'OnFilterChange',

  HttpRequestInited = 'HttpRequestInited',
  HttpRequestResult = 'HttpRequestResult',
  HttpRawFetch = 'HttpRawFetch',
  HttpFetchCancel = 'HttpFetchCancel',
  HttpFetchSend = 'HttpFetchSend',
  HttpFetchReadBody = 'HttpFetchReadBody',

  // Clipboard
  ClipboardHasText = 'ClipboardHasText',
  ClipboardHasImage = 'ClipboardHasImage',
  ClipboardHasHtml = 'ClipboardHasHtml',
  ClipboardHasRtf = 'ClipboardHasRtf',
  ClipboardHasFiles = 'ClipboardHasFiles',
  ClipboardWriteText = 'ClipboardWriteText',
  ClipboardWriteHtml = 'ClipboardWriteHtml',
  ClipboardWriteHtmlAndText = 'ClipboardWriteHtmlAndText',
  ClipboardWriteRtf = 'ClipboardWriteRtf',
  ClipboardWriteFilesUris = 'ClipboardWriteFilesUris',
  ClipboardWriteFiles = 'ClipboardWriteFiles',
  ClipboardClear = 'ClipboardClear',
  ClipboardReadText = 'ClipboardReadText',
  ClipboardReadHtml = 'ClipboardReadHtml',
  ClipboardReadRtf = 'ClipboardReadRtf',
  ClipboardReadFiles = 'ClipboardReadFiles',
  ClipboardReadFilesUris = 'ClipboardReadFilesUris',
  ClipboardReadImageBinary = 'ClipboardReadImageBinary',
  ClipboardReadImageBase64 = 'ClipboardReadImageBase64',
  ClipboardWriteImageBinary = 'ClipboardWriteImageBinary',
  ClipboardWriteImageBase64 = 'ClipboardWriteImageBase64',

  // Dialog
  DialogAsk = 'DialogAsk',
  DialogConfirm = 'DialogConfirm',
  DialogMessage = 'DialogMessage',
  DialogOpen = 'DialogOpen',
  DialogSave = 'DialogSave',

  // File System
  FsReadDir = 'FsReadDir',
  FsReadFile = 'FsReadFile',
  // FsOpen = 'FsOpen',
  FsReadTextFile = 'FsReadTextFile',
  // FsReadTextFileLines = 'FsReadTextFileLines',
  FsStat = 'FsStat',
  FsLstat = 'FsLstat',
  FsExists = 'FsExists',
  // FsWatch = 'FsWatch',
  FsMkdir = 'FsMkdir',
  FsCreate = 'FsCreate',
  FsCopyFile = 'FsCopyFile',
  FsRemove = 'FsRemove',
  FsRename = 'FsRename',
  FsTruncate = 'FsTruncate',
  FsWriteFile = 'FsWriteFile',
  FsWriteTextFile = 'FsWriteTextFile',
  // Shell
  ShellxExecute = 'ShellxExecute',
  ShellxKill = 'ShellxKill',
  ShellxStdinWrite = 'ShellxStdinWrite',
  ShellxOpen = 'ShellxOpen',
  ShellxSpawn = 'ShellxSpawn',
  // Notification
  NotificationSendNotification = 'NotificationSendNotification',
  NotificationRequestPermission = 'NotificationRequestPermission',
  NotificationIsPermissionGranted = 'NotificationIsPermissionGranted',
  // OS
  OsPlatform = 'OsPlatform',
  OsArch = 'OsArch',
  OsExeExtension = 'OsExeExtension',
  OsFamily = 'OsFamily',
  OsHostname = 'OsHostname',
  OsEol = 'OsEol',
  OsVersion = 'OsVersion',
  OsLocale = 'OsLocale',
}
