import { type Remote } from '@huakunshen/comlink'
import {
  appCacheDir,
  appConfigDir,
  appDataDir,
  appLocalDataDir,
  appLogDir,
  audioDir,
  basename,
  cacheDir,
  configDir,
  dataDir,
  delimiter,
  desktopDir,
  dirname,
  documentDir,
  downloadDir,
  executableDir,
  extname,
  fontDir,
  homeDir,
  isAbsolute,
  join,
  localDataDir,
  normalize,
  pictureDir,
  publicDir,
  resolve,
  resolveResource,
  resourceDir,
  runtimeDir,
  sep,
  tempDir,
  templateDir,
  videoDir,
} from '@tauri-apps/api/path'
import { defaultClientAPI, isMain } from '../client'
import { type IPath } from './client-types'
import { type IPathServer } from './server-types'

export function constructAPI(api: Remote<IPathServer>): IPath {
  return {
    appCacheDir: api.appCacheDir,
    appConfigDir: api.appConfigDir,
    appDataDir: api.appDataDir,
    appLocalDataDir: api.appLocalDataDir,
    appLogDir: api.appLogDir,
    audioDir: api.audioDir,
    basename: api.basename,
    cacheDir: api.cacheDir,
    configDir: api.configDir,
    dataDir: api.dataDir,
    delimiter: api.delimiter as any,
    desktopDir: api.desktopDir,
    dirname: api.dirname,
    documentDir: api.documentDir,
    downloadDir: api.downloadDir,
    executableDir: api.downloadDir,
    extname: api.extname,
    fontDir: api.fontDir,
    homeDir: api.homeDir,
    isAbsolute: api.isAbsolute,
    join: api.join,
    localDataDir: api.localDataDir,
    normalize: api.normalize,
    pictureDir: api.pictureDir,
    publicDir: api.publicDir,
    resolve: api.resolve,
    resolveResource: api.resolveResource,
    resourceDir: api.resourceDir,
    runtimeDir: api.runtimeDir,
    sep: api.sep as any,
    tempDir: api.tempDir,
    templateDir: api.templateDir,
    videoDir: api.videoDir,
  }
}
export const comlinkPath: IPath = constructAPI(defaultClientAPI)
export const nativePath: IPath = {
  appCacheDir,
  appConfigDir,
  appDataDir,
  appLocalDataDir,
  appLogDir,
  audioDir,
  basename,
  cacheDir,
  configDir,
  dataDir,
  delimiter,
  desktopDir,
  dirname,
  documentDir,
  downloadDir,
  executableDir,
  extname,
  fontDir,
  homeDir,
  isAbsolute,
  join,
  localDataDir,
  normalize,
  pictureDir,
  publicDir,
  resolve,
  resolveResource,
  resourceDir,
  runtimeDir,
  sep,
  tempDir,
  templateDir,
  videoDir,
}

export const path = isMain ? nativePath : comlinkPath
